<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Poprawne i nie poprawne logowanie do aplikacji</description>
   <name>TS01 - Logowanie do aplikacji</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f2de8e87-9c41-4521-8358-91ffc9d72fc6</testSuiteGuid>
   <testCaseLink>
      <guid>8e5c9727-6a41-4ca3-a731-4dab5ba12f60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Podstawowe funkcjonalnosci/Logowanie do aplikacji/Logowanie do aplikacji z niepoprawnym formatem danych</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1d86077-c1bf-4ac7-8acf-f34347be1a6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3276014-1850-4295-9fac-9820e49544c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d411ece-8683-49fc-801e-87bec18ec06b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>530feada-f8bc-40cf-baf7-836191206ac6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39c00073-60f3-4878-acbf-6da433c3fe4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bae09596-2b12-42c8-9362-312735e050fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc05474c-316b-4a79-882c-088642c584d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cde7e8d5-c9bb-43fd-9601-270f9f118f13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Podstawowe funkcjonalnosci/Logowanie do aplikacji/Logowanie do aplikacji z poprawnymi danymi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>365e6a51-4221-4f64-8f75-c3889f7c2c25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>490ef2b6-faeb-4ea1-8110-6f0bf47ffff0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcd90cb4-551d-4a21-95ea-0b912f68148d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
